### PR TITLE
Security and Maintenance update

### PR DESCRIPTION
**Pull request by FrancoisTrible**
See https://www.ibm.com/support/pages/node/6333583

### CODE REVIEW

**Review by lpchitta — APPROVED** [review]
Looks good to me with all the image tags updated.

**Comment by TiloGit** [comment]
default image value for UMS is bad it seems. 
Normal BackOff 5s (x15 over 3m46s) kubelet, 10.241.50.186 Back-off pulling image "**cp.icr.io/cp/cp4a/ums/ums:20.0.2.1**"

Looks like it should be **20.0.2-IF001**

**Comment by TiloGit** [comment]
@FrancoisTrible beside UMS also JMS for BAW **cp.icr.io/cp/cp4a/baw/jms:20.0.1**

the logic for identifying Tag based on version need to be updated or tag the image different. (for default without specify value in CR)

**Comment by ibmfjk** [comment]
@TiloGit @FrancoisTrible For workflow/workstreams deployment, only FC(fully customizable) template is supported in 20.0.2-IF001(20.0.2.1), so the repository and tag for jms should always be specified explicitly.

https://github.com/icp4a/cert-kubernetes/blob/master/descriptors/patterns/ibm_cp4a_cr_enterprise_FC_workflow-workstreams.yaml#L588
https://github.com/icp4a/cert-kubernetes/blob/master/descriptors/patterns/ibm_cp4a_cr_enterprise_FC_workflow.yaml#L570
https://github.com/icp4a/cert-kubernetes/blob/master/descriptors/patterns/ibm_cp4a_cr_enterprise_FC_workstreams.yaml#L540

**Pull request merged**
